const $aside = $("[data-name='aside']");
const $asideColumn = $("[data-name='asideColumn']");
const $asideNav = $("[data-name='asideNav']");
const $buttonAdd = $("[data-action='addTask']");
const $buttonMenu = $("[data-action='manageMenu']");
const $inputSearch = $("[data-action='searchTasks']");
const $list = $("[data-name='list']");
const $main = $("[data-name='main']")
const $selectSort = $("[data-action='sortTasks']");
const $todo = $("[data-name='todo']");